### ISSUE TITLE
[rubocop] Allow the inline use of the private keyword

### ISSUE THREAD

**Issue by JoakimKlaxit** [klaxit/ruby#20]
Hi Klaxit !

Rubocop rules, especially on metrics, often require the creation of one or more private methods after cutting a public method, to improve code reading.
However, since the use of the `Style/AccessModifyDeclarations` rule requires private methods to be grouped together, this makes it more difficult to read the code, because the grouping of methods is no longer based on a functional but a technical criterion.

I propose that you remove the use of the `convention:Style/AccessModifyDeclarations` rule to allow a private method to be written next to its public method, as is frequently seen in other languages.

Example :  

```ruby
def method(arg)
  private_method(arg)
end

private def private_method(arg)
  #...
end
```

What do you think?

**Comment by pyrsmk** [comment]
100% with you, mate !

**Comment by BuonOmo** [comment]
> I propose that you remove the use of the convention:Style/AccessModifyDeclarations rule to allow a private method to be written next to its public method, as is frequently seen in other languages.

I'd rather not remove the rule but **enforce** it. This is how stripe write it's code and it find it way clearer than having a `private`, `module_function` or `protected` somwhere in the file... See this bit for instance: https://github.com/stripe/stripe-ruby/blob/master/lib/stripe/stripe_object.rb#L516-L562

**Comment by ThomasKlaxit** [comment]
I'm all for it! 👍

**Comment by ccyrille** [comment]
I don't agree mixing public / protected / private methods is a good pratice. When you discover a class, all you want to see is its public methods. You are far better having them at the beginning (mixing them with protected / private ones doesn't help readability of the class overall). Please keep in mind that not everybody use an advanced editor as you do ^^ Happy to talk about it !

**Comment by pyrsmk** [comment]
The problem is that it's not obvious that a method is private until you have found where the `private` keyword is placed in the class. To me : the more explicit the better.

Besides that, I agree, when we're viewing a class we're searching for its public methods. In that case, maybe it should be a rubocop rule to enforce the order of methods according to their access modifiers.

**Comment by JoakimKlaxit** [comment]
Being able to list public methods easily is a good argument, but in my experience, I spend much more time trying to understand a feature of a class than wondering what the public methods of that class are.
In other words, should encapsulation take precedence over readability and ease of understanding of the code? As the developer of the code in question, I don't think, as a simple user of this code, for example for a third-party library, maybe, but normally, isn't it the responsibility of the documentation to tell us how to use a class ?

**Comment by JoakimKlaxit** [comment]
The question has already been asked ! A link to give you an idea of the different arguments! https://stackoverflow.com/questions/1760850/best-practice-ordering-of-public-protected-private-within-the-class-definition

**Comment by BuonOmo** [comment]
@ccyrille I'm OK for keeping a public / protected / private order. This is quite easy to do IMHO, @hugobarthelemy @JoakimKlaxit can you give your feedback on implementing a rubocop rule for that?
